In [4]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [6]:
tf

<module 'tensorflow' from 'C:\\Users\\Anirban Banerjee\\.conda\\envs\\tf\\lib\\site-packages\\tensorflow\\__init__.py'>

In [7]:
dataset=pd.read_csv(r"D:\Deep Learning\Machine Learning A-Z (Codes and Datasets)\Part 8 - Deep Learning\Section 39 - Artificial Neural Networks (ANN)\Python\Churn_Modelling.csv")

In [11]:
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [12]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [13]:
print(y)

[1 0 1 ... 1 1 0]


In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [16]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [17]:
print(y)

[1 0 1 ... 1 1 0]


In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [20]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [22]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [23]:
ann=tf.keras.models.Sequential()

In [24]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [25]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [26]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [27]:
ann.compile(optimizer='adam' ,loss='binary_crossentropy' ,metrics=['accuracy'])

In [28]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6143 - accuracy: 0.7314
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4718 - accuracy: 0.8096
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4295 - accuracy: 0.8189
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4182 - accuracy: 0.8219
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4133 - accuracy: 0.8270
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4100 - accuracy: 0.8280
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4075 - accuracy: 0.8281
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4058 - accuracy: 0.8274
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4037 - accuracy: 0.8285
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4016 - accura

250/250 [==============================] - 0s 2ms/step - loss: 0.3383 - accuracy: 0.8609
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3376 - accuracy: 0.8616
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3377 - accuracy: 0.8633
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3373 - accuracy: 0.8633
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3377 - accuracy: 0.8609
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3368 - accuracy: 0.8609
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3369 - accuracy: 0.8619
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3370 - accuracy: 0.8622
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3366 - accuracy: 0.8634
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3372 - accuracy: 

In [32]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 19ms/step
[[False]]


In [36]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1501   94]
 [ 196  209]]


0.855